src/Blog/Controller/HomeController.php
<?php
namespace Frame\Module\Blog\Controller;

use Frame\Controller\Controller;

class HomeController extends Controller
{
    public function get(){
    	return $this->render('@Blog/public/article');
    }
}

src/Blog/Controller/PrivateArticleController.php
<?php
namespace Frame\Module\Blog\Controller;

use Frame\Module\Admin\Controller\ModuleSettingsController;

use Frame\Module\Blog\Model\BlogArticle;
use Frame\Module\Blog\Model\BlogCategory;

class PrivateArticleController extends ModuleSettingsController
{
	protected $file = '@Blog/private/article.twig';

	public function getEdit(){
		return parent::get();
	}

	public function postEdit(){
		//update
		$article = $this->request->getAttribute('current_article');

		foreach($article->getAttributes() as $attribute => $value){
			if($this->param($attribute)){
				$article->$attribute = $this->param($attribute);
			}
		}

		$article->save();

		$this->flash('success', $this->translator->lang('@Blog.article.updated'));

		return $this->redirect('@Blog.settings');
	}

	public function getCreate(){
		return parent::get();
	}

	public function postCreate(){
		// create
		//dd($this->param('category_id'));
		BlogArticle::create([
			'name' => $this->param('name'),
			'slug' => $this->param('slug'),
			'category_id' => $this->param('category_id'),
			'content' => $this->param('content')
		]);

		$this->flash('success', $this->translator->lang('@Blog.article.created'));

		return $this->redirect('@Blog.settings');
	}

	public function getArgs(){
		return [
			'categories' => array_map(function($item){
				return ['value' => $item['id'], 'label' => $item['name']];
			}, BlogCategory::get()->toArray())
		];
	}
}

src/Blog/Controller/PrivateCategoryController.php
<?php
namespace Frame\Module\Blog\Controller;

use Frame\Module\Admin\Controller\ModuleSettingsController;

use Frame\Module\Blog\Model\BlogCategory;

class PrivateCategoryController extends ModuleSettingsController
{
	protected $file = '@Blog/private/article.twig';

	public function getEdit(){
		return parent::get();
	}

	public function postEdit(){
		//update
		$category = $this->request->getAttribute('current_category');

		foreach($category->getAttributes() as $attribute => $value){
			if($this->param($attribute)){
				$category->$attribute = $this->param($attribute);
			}
		}

		$category->save();

		return $this->redirect('@Blog.settings');
	}

	public function getCreate(){
		return parent::get();
	}

	public function postCreate(){
		// create
		BlogCategory::create([
			'name' => $this->param('name'),
			'slug' => $this->param('slug')
		]);

		$this->flash('succes', $this->translator->lang('@Blog.category.created'));

		return $this->redirect('@Blog.settings');
	}

	public function getArgs(){
		return [
			'categories' => array_map(function($item){
				return ['value' => $item['id'], 'label' => $item['name']];
			}, BlogCategory::get()->toArray())
		];
	}
}

src/Blog/Controller/PublicArticleController.php
<?php
namespace Frame\Module\Blog\Controller;

use Frame\Controller\Controller;

class PublicArticleController extends Controller
{
    public function get(){
    	return $this->render('@Blog/public/article');
    }
}

src/Blog/Controller/PublicCategoryController.php
<?php
namespace Frame\Module\Blog\Controller;

use Frame\Controller\Controller;

class PublicCategoryController extends Controller
{
    public function get(){

    }
}

src/Blog/Controller/SettingsController.php
<?php
namespace Frame\Module\Blog\Controller;

use Frame\Controller\Controller;
use Frame\Module\Admin\Controller\ModuleSettingsController;

use Frame\Module\Blog\Model\BlogArticle;
use Frame\Module\Blog\Model\BlogCategory;

class SettingsController extends ModuleSettingsController
{
    protected $file = '@Blog/pages/settings.twig';

    public function getArgs(){
    	//dd(BlogArticle::get());
    	return [
    		'categories' => BlogCategory::with('article')->get()
    	];
    }
}

templates/Domain/components/alerts.twig
{% for key, notification in flash.getMessages() %}
    <div class="notification-box -{{ key }}" role="alert">
        {{ notification.0 | raw }} 
    </div>
{% endfor %}

templates/Domain/components/breadcrumb.twig
<div class='bread-crumb -no-margin'>
	{% set uri = path_for(route.getName, route.getArguments)|replace({(getenv('APP_URI')):''}) %}
	{% set paths = uri|split('/') %}

	{% for path in paths %}
	    {% if path is not empty %}
	    	{% set dadIndex = loop.index %}
	    	{% set buildedPath = getenv('APP_URI') %}
	    	{% for _path in paths %}
	    		{% if loop.index <= dadIndex and _path is not empty %}
	    			{% set buildedPath = buildedPath ~ '/' ~ _path %}
	    		{% endif %}
	    	{% endfor %}
	    	<a href="{{ buildedPath }}" class='item'>{{ path }}</a>
	    	{% if paths[loop.index] is not empty %}
	    		<span class='separator'></span>
	    	{% endif %}
	    {% endif %}
	{% endfor %}
</div>

templates/Domain/components/form/input-color.twig
{% extends '@Domain/components/form/input.twig' %}

{% block input %}
    <label class='input-color {{ container_class }}{% if attribute(errors, name) != null %} -error{% endif %}'
        {% for name, value in props %}
            {{ name }}='{{ value }}'
        {% endfor %}
    >
        <input type="color" name='{{ name }}' id='{{ name }}' class='input {{ class }}' value='{{ value | default(attribute(old, name)) }}'>
        <span class="prefix"></span>
        <span class="value"></span>
    </label>
{% endblock %}

templates/Domain/components/form/input-file.twig
{% extends '@Domain/components/form/input.twig' %}

{% block input %}
    <label class='input-file {{ container_class }}{% if attribute(errors, name) != null %} -error{% endif %}'
        {% for name, value in props %}
            {{ name }}='{{ value }}'
        {% endfor %}
    >
        <input type="file" name='{{ name }}' id='{{ name }}' class='input {{ class }}' value='{{ value | default(attribute(old, name)) }}'>
        <span class="prefix"></span>
        <span class="value"></span>
    </label>
{% endblock %}

templates/Domain/components/form/input.twig
{% if not(nofield | default(false)) %}
    <div class="form-field {{ field_class }}"
        {% for name, value in field_props %}
            {{ name }}='{{ value }}'
        {% endfor %}
    >
{% endif %}

    {% if wrap | default(false) %}
        <div>
    {% endif %}

    {% if label | default(false) or translated | default(false) %}
        {% if translated != null %}
            {% set label = translator.lang(translated.label, translated.args | default({})) %}
        {% endif %}
        <label class="label" for='{{ name }}'>{{ label }}</label>
    {% endif %}
    
    {% block input %}
        <input type="{{ type | default('text') }}" {% if name != null %}name='{{ name }}' id='{{ name }}'{% endif %} class='{{ class }}{% if attribute(errors, name) != null %} -error{% endif %}' value='{{ value | default(attribute(old, name)) }}' 
        {% for name, value in props %}
            {{ name }}='{{ value }}'
        {% endfor %}
        >
    {% endblock %}

    {% if attribute(errors, name) != null %}
        {% if attribute(errors, name) is iterable %}
            {% for error in attribute(errors, name) %}
                <div class="help -error">{{error}}</div>
            {% endfor %}
        {% else %}
            <div class="help -error">{{attribute(errors, name)}}</div>
        {% endif %}
    {% endif %}

    {% if wrap | default(false) %}
        </div>
    {% endif %}

{% if not(nofield | default(false)) %}
    </div>
{% endif %}

templates/Domain/components/form/select.twig
{% extends '@Domain/components/form/input.twig' %}

{% block input %}
    <div class="select" 
        {% for name, value in props %}
            {{ name }}='{{ value }}'
        {% endfor %}
    >
        <select name="{{ name }}" id='{{ name }}' class='{{ class }}'>
            {% for option in options %}
                {% set inputValue = option.value | default(option) %}
                {% set inputLabel = option.label | default(option) %}
                {% set selected = (value == inputValue ? ' selected' : '') %}

                {% if translated_options != null %}
                    {% set inputLabel = translator.lang(translated_options ~ '.' ~ inputLabel|lower) %}
                {% endif %}

                <option value="{{ inputValue }}"{{ selected }}>{{ inputLabel }}</option>
            {% endfor %}
        </select>
    </div>
{% endblock %}

templates/Domain/components/form/textarea.twig
{% extends '@Domain/components/form/input.twig' %}

{% block input %}
    <textarea type="file" name='{{ name }}' id='{{ name }}' class='{{ class }}{% if attribute(errors, name) != null %} -error{% endif %}'>{{ value | default(attribute(old, name)) | default('') }}</textarea>
{% endblock %}

templates/Domain/components/link.twig
{% macro link(path, label, class, exact, path_opt, data) %}
	{% set path_opt = path_opt | default({}) %}
	{% set active = path_for(path, path_opt) in path_for(route.getName(), route.getArguments()) %}
	{% if exact %}
		{% set active = path == route.getName() %}
	{% endif %}

    <a class="{{ class | default('') }}{{ active ? ' -focus' : '' }}" href="{{ path_for(path, path_opt) }}">{{ label | default(path) }}{{ data.child | default('') | raw }}</a>
{% endmacro %}

templates/Domain/components/login-item.twig
{% import '@Domain/components/link.twig' as html %}

{% if auth.check() %}
	<span class="drop-down" tabindex="0">
		<span class="toggle -lighty -prefixed" id="accountMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
			<span class="prefix"><i class="ico ico-account"></i></span>
			{{ auth.username }}
		</span>
		<div class="drop-content" aria-labelledby="accountMenu">
			<div class="drop-block -list">
				{{ html.link('auth.settings', translator.lang('@Auth.parts.setting'), 'item') }}
				{{ html.link('auth.logout', translator.lang('@Auth.parts.logout'), 'item -error') }}
			</div>
		</div>
	</span>
{% else %}
	{{ html.link('auth.login', translator.lang('@Auth.parts.login'), 'nav-item -success') }}
	{{ html.link('auth.register', translator.lang('@Auth.parts.register'), 'nav-item') }}
{% endif %}

templates/Domain/components/nav.twig
{% import '@Domain/components/link.twig' as html %}

<div class='side-bar -scrollable' id='side-bar'>
	<div class="side-toggle" grid='padded'>
		<a class='side-open' href='#side-bar'>
			<i class="ico ico-chevron-right"></i>
		</a>
		<a class='side-close' href='#'>
			<i class="ico ico-chevron-right"></i>
		</a>
	</div>
	<div grid='gutters middle list' column>
		<div class="group-block -vertical">
			<button class='button -darky -square'><i class='-flat ico ico-flag-variant ico-right'></i>France</button>
			<button class='button -darky -square'><i class='-flat ico ico-city ico-right'></i>Saint-Nazaire</button>
			<button class='button -darky -square' data-action='copy' data-trigger='click'><i class='-flat ico ico-email ico-right'></i><span data-target>bouscharain.jonas@hotmail.fr</span></button>
			<button class='button -darky -square' data-action='copy' data-trigger='click'><i class='-flat ico ico-phone ico-right'></i><span data-target>+33605279908</span></button>
		</div>
		<div><hr></div>
		<div grid='list gutters no-shrink' column>
			<span class='simple-title'>Navigation</span>
			{% for item in global().navbar.main %}
				{% include item.file with item.args | default({}) %}
			{% endfor %}
		</div>
		<div grid='list gutters'>
			{% for item in global().navbar.right %}
				{% include item.file with item.args | default({}) %}
			{% endfor %}
		</div>
	</div>
</div>

templates/Domain/layout/app.twig
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">

        <link rel="icon" type="image/png" href="{{ asset('favicon-16x16.png') }}" sizes="16x16">
        <link rel="icon" type="image/png" href="{{ asset('favicon-32x32.png') }}" sizes="32x32">
        <link rel="icon" type="image/png" href="{{ asset('favicon-64x64.png') }}" sizes="64x64">

        <link rel="stylesheet" type="text/css" href="https://gl.githack.com/Jonas-B/frame-css/raw/master/dist/frame.css">

        {% block styles %}{% endblock %}

        <title>{{ getenv('APP_NAME', 'My App') }} - {{ route.getName() | split('.') | last | capitalize }}</title>
    </head>
    <body grid='fluid' class='theme'>
        {% include '@Domain/components/nav.twig'%}

        <div class="content" column>
            {% block content %}{% endblock %}
        </div>

        <script type="text/javascript" src='{{ asset('js/domain/util.js') }}'></script>

        {% block scripts %}{% endblock %}
    </body>
</html>

templates/Domain/link.twig
{% set path_opt = path_opt | default({}) %}
{% set active = path_for(path, path_opt) in path_for(route.getName(), route.getArguments()) %}
{% if exact %}
    {% set active = path == route.getName() %}
{% endif %}
{% if translated != null %}
    {% set label = translator.lang(translated.label, translated.args | default({})) %}
{% endif %}

<a class="{{ class | default('') }}{{ active ? ' -focus' : '' }}{{ badged != null ? ' -badged' : '' }}" href="{{ path_for(path, path_opt) }}">
    {% if ico != null %}
        <i class="ico ico-{{ ico }} ico-right"></i>
    {% endif %}
    {% if prefix != null %}
        <span class="{{ prefix.class }}" {% for key, value in prefix.props|default({}) %} {{ key }}="{{ value }}"{% endfor %}>{{ prefix.content | default('') }}</span>
    {% endif %}
    {{ label | default(path) }}{{ child | default('') | raw }}

    {% if badged != null %}
        <span class='badge {{ badged.class | default('') }}'>{{ badged.content }}</span>
    {% endif %}
</a>

templates/Domain/pages/home.twig
{% extends '@Domain/layout/app.twig' %}

{% block content %}
	<div grid='center middle' class='_size-fluid'>
		<h2>Coming soon...</h2>
	</div>
{% endblock %}